spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.1.103:3307/weblog2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: Weblog-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  security:
    user:
      name: admin # 登录用户名
      password: 123456 # 登录密码

#=================================================================
# minio (上传图片需要，需配置成自己的地址)
#=================================================================
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: quanxiaoha
  secretKey: quanxiaoha
  bucketName: weblog

#=================================================================
# Lucene 全文检索
#=================================================================
lucene:
  indexDir: E:\\java_workspace\\lucene-index # lucene 索引存放的位置